package com.xtgg.model;

import com.xtgg.model.base.BaseAreainfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Areainfo extends BaseAreainfo<Areainfo> {
	public static final Areainfo dao = new Areainfo();
}
