package com.xtgg.model;

import com.xtgg.model.base.BaseClientExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientExtend extends BaseClientExtend<ClientExtend> {
	public static final ClientExtend dao = new ClientExtend();
}
