package com.xtgg.model;

import com.xtgg.model.base.BaseClientUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientUpload extends BaseClientUpload<ClientUpload> {
	public static final ClientUpload dao = new ClientUpload();
}
