package com.xtgg.model;

import com.xtgg.model.base.BaseClientLastTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientLastTime extends BaseClientLastTime<ClientLastTime> {
	public static final ClientLastTime dao = new ClientLastTime();
}
