package com.xtgg.model;

import com.xtgg.model.base.BaseClientHobby;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientHobby extends BaseClientHobby<ClientHobby> {
	public static final ClientHobby dao = new ClientHobby();
}
