package com.xtgg.model;

import com.xtgg.model.base.BaseClientFamilyRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientFamilyRelation extends BaseClientFamilyRelation<ClientFamilyRelation> {
	public static final ClientFamilyRelation dao = new ClientFamilyRelation();
}
