package com.xtgg.model;

import com.xtgg.model.base.BaseClientQuestionnaire;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientQuestionnaire extends BaseClientQuestionnaire<ClientQuestionnaire> {
	public static final ClientQuestionnaire dao = new ClientQuestionnaire();
}
