package com.xtgg.model;

import com.xtgg.model.base.BaseClientHealth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientHealth extends BaseClientHealth<ClientHealth> {
	public static final ClientHealth dao = new ClientHealth();
}
