package com.xtgg.model;

import com.xtgg.model.base.BaseClientMentalHealth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientMentalHealth extends BaseClientMentalHealth<ClientMentalHealth> {
	public static final ClientMentalHealth dao = new ClientMentalHealth();
}
