package com.xtgg.model;

import com.xtgg.model.base.BaseClientFamilyHealth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientFamilyHealth extends BaseClientFamilyHealth<ClientFamilyHealth> {
	public static final ClientFamilyHealth dao = new ClientFamilyHealth();
}
