package com.xtgg.model;

import com.xtgg.model.base.BaseClientDiseaseSelf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientDiseaseSelf extends BaseClientDiseaseSelf<ClientDiseaseSelf> {
	public static final ClientDiseaseSelf dao = new ClientDiseaseSelf();
}
