package com.xtgg.model;

import com.xtgg.model.base.BaseClientServiceRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientServiceRemind extends BaseClientServiceRemind<ClientServiceRemind> {
	public static final ClientServiceRemind dao = new ClientServiceRemind();
}
