package com.xtgg.model;

import com.xtgg.model.base.BaseClientFollowup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientFollowup extends BaseClientFollowup<ClientFollowup> {
	public static final ClientFollowup dao = new ClientFollowup();
}
