package com.xtgg.model;

import com.xtgg.model.base.BaseClientPhysical;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientPhysical extends BaseClientPhysical<ClientPhysical> {
	public static final ClientPhysical dao = new ClientPhysical();
}
