package com.xtgg.model;

import com.xtgg.model.base.BaseClientDiseaseFamily;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientDiseaseFamily extends BaseClientDiseaseFamily<ClientDiseaseFamily> {
	public static final ClientDiseaseFamily dao = new ClientDiseaseFamily();
}
