package com.xtgg.model;

import com.xtgg.model.base.BaseClientLatestPhysical;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientLatestPhysical extends BaseClientLatestPhysical<ClientLatestPhysical> {
	public static final ClientLatestPhysical dao = new ClientLatestPhysical();
}
