package com.xtgg.model;

import com.xtgg.model.base.BaseClientinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clientinfo extends BaseClientinfo<Clientinfo> {
	public static final Clientinfo dao = new Clientinfo();
	
}
