package com.xtgg.model;

import com.xtgg.model.base.BaseClientDiet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientDiet extends BaseClientDiet<ClientDiet> {
	public static final ClientDiet dao = new ClientDiet();
}
