package com.xtgg.model;

import com.xtgg.model.base.BaseSourceConstant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SourceConstant extends BaseSourceConstant<SourceConstant> {
	public static final SourceConstant dao = new SourceConstant();
}
