package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientPhysical<M extends BaseClientPhysical<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setMedicalCenter(java.lang.String medicalCenter) {
		set("medicalCenter", medicalCenter);
	}

	public java.lang.String getMedicalCenter() {
		return get("medicalCenter");
	}

	public void setMedicalNo(java.lang.String medicalNo) {
		set("medicalNo", medicalNo);
	}

	public java.lang.String getMedicalNo() {
		return get("medicalNo");
	}

	public void setPhysicalTime(java.util.Date physicalTime) {
		set("physicalTime", physicalTime);
	}

	public java.util.Date getPhysicalTime() {
		return get("physicalTime");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setSuggest(java.lang.String suggest) {
		set("suggest", suggest);
	}

	public java.lang.String getSuggest() {
		return get("suggest");
	}

	public void setFilePath(java.lang.String filePath) {
		set("filePath", filePath);
	}

	public java.lang.String getFilePath() {
		return get("filePath");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
