package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientMentalHealth<M extends BaseClientMentalHealth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setDepress(java.lang.Boolean depress) {
		set("depress", depress);
	}

	public java.lang.Boolean getDepress() {
		return get("depress");
	}

	public void setEvent(java.lang.String event) {
		set("event", event);
	}

	public java.lang.String getEvent() {
		return get("event");
	}

	public void setEventSupply(java.lang.String eventSupply) {
		set("eventSupply", eventSupply);
	}

	public java.lang.String getEventSupply() {
		return get("eventSupply");
	}

	public void setExcite(java.lang.Boolean excite) {
		set("excite", excite);
	}

	public java.lang.Boolean getExcite() {
		return get("excite");
	}

	public void setFuel(java.lang.Boolean fuel) {
		set("fuel", fuel);
	}

	public java.lang.Boolean getFuel() {
		return get("fuel");
	}

	public void setHappy(java.lang.Boolean happy) {
		set("happy", happy);
	}

	public java.lang.Boolean getHappy() {
		return get("happy");
	}

	public void setHope(java.lang.Boolean hope) {
		set("hope", hope);
	}

	public java.lang.Boolean getHope() {
		return get("hope");
	}

	public void setLongly(java.lang.Boolean longly) {
		set("longly", longly);
	}

	public java.lang.Boolean getLongly() {
		return get("longly");
	}

	public void setMelancholy(java.lang.Boolean melancholy) {
		set("melancholy", melancholy);
	}

	public java.lang.Boolean getMelancholy() {
		return get("melancholy");
	}

	public void setNerves(java.lang.Boolean nerves) {
		set("nerves", nerves);
	}

	public java.lang.Boolean getNerves() {
		return get("nerves");
	}

	public void setPet(java.lang.Boolean pet) {
		set("pet", pet);
	}

	public java.lang.Boolean getPet() {
		return get("pet");
	}

	public void setPfEquipment(java.lang.Boolean pfEquipment) {
		set("pfEquipment", pfEquipment);
	}

	public java.lang.Boolean getPfEquipment() {
		return get("pfEquipment");
	}

	public void setToilet(java.lang.Boolean toilet) {
		set("toilet", toilet);
	}

	public java.lang.Boolean getToilet() {
		return get("toilet");
	}

	public void setWater(java.lang.Boolean water) {
		set("water", water);
	}

	public java.lang.Boolean getWater() {
		return get("water");
	}

}
