package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientLatestPhysical<M extends BaseClientLatestPhysical<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setAlb(java.lang.String alb) {
		set("alb", alb);
	}

	public java.lang.String getAlb() {
		return get("alb");
	}

	public void setBk(java.lang.String bk) {
		set("bk", bk);
	}

	public java.lang.String getBk() {
		return get("bk");
	}

	public void setBreech(java.lang.String breech) {
		set("breech", breech);
	}

	public java.lang.String getBreech() {
		return get("breech");
	}

	public void setBun(java.lang.String bun) {
		set("bun", bun);
	}

	public java.lang.String getBun() {
		return get("bun");
	}

	public void setDbil(java.lang.String dbil) {
		set("dbil", dbil);
	}

	public java.lang.String getDbil() {
		return get("dbil");
	}

	public void setDbp(java.lang.String dbp) {
		set("dbp", dbp);
	}

	public java.lang.String getDbp() {
		return get("dbp");
	}

	public void setGlu(java.lang.String glu) {
		set("glu", glu);
	}

	public java.lang.String getGlu() {
		return get("glu");
	}

	public void setHdl(java.lang.String hdl) {
		set("hdl", hdl);
	}

	public java.lang.String getHdl() {
		return get("hdl");
	}

	public void setHeight(java.lang.String height) {
		set("height", height);
	}

	public java.lang.String getHeight() {
		return get("height");
	}

	public void setLdl(java.lang.String ldl) {
		set("ldl", ldl);
	}

	public java.lang.String getLdl() {
		return get("ldl");
	}

	public void setNatrium(java.lang.String natrium) {
		set("natrium", natrium);
	}

	public java.lang.String getNatrium() {
		return get("natrium");
	}

	public void setSbp(java.lang.String sbp) {
		set("sbp", sbp);
	}

	public java.lang.String getSbp() {
		return get("sbp");
	}

	public void setScre(java.lang.String scre) {
		set("scre", scre);
	}

	public java.lang.String getScre() {
		return get("scre");
	}

	public void setSgot(java.lang.String sgot) {
		set("sgot", sgot);
	}

	public java.lang.String getSgot() {
		return get("sgot");
	}

	public void setSgpt(java.lang.String sgpt) {
		set("sgpt", sgpt);
	}

	public java.lang.String getSgpt() {
		return get("sgpt");
	}

	public void setTbil(java.lang.String tbil) {
		set("tbil", tbil);
	}

	public java.lang.String getTbil() {
		return get("tbil");
	}

	public void setTc(java.lang.String tc) {
		set("tc", tc);
	}

	public java.lang.String getTc() {
		return get("tc");
	}

	public void setTlc(java.lang.String tlc) {
		set("tlc", tlc);
	}

	public java.lang.String getTlc() {
		return get("tlc");
	}

	public void setWaist(java.lang.String waist) {
		set("waist", waist);
	}

	public java.lang.String getWaist() {
		return get("waist");
	}

	public void setHeartRate(java.lang.String heartRate) {
		set("heartRate", heartRate);
	}

	public java.lang.String getHeartRate() {
		return get("heartRate");
	}

	public void setWeight(java.lang.String weight) {
		set("weight", weight);
	}

	public java.lang.String getWeight() {
		return get("weight");
	}

	public void setHbalc(java.lang.String hbalc) {
		set("hbalc", hbalc);
	}

	public java.lang.String getHbalc() {
		return get("hbalc");
	}

	public void setNiddmType(java.lang.Integer niddmType) {
		set("niddmType", niddmType);
	}

	public java.lang.Integer getNiddmType() {
		return get("niddmType");
	}

	public void setPhysicalTime(java.util.Date physicalTime) {
		set("physicalTime", physicalTime);
	}

	public java.util.Date getPhysicalTime() {
		return get("physicalTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
