package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientHealth<M extends BaseClientHealth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setBear(java.lang.String bear) {
		set("bear", bear);
	}

	public java.lang.String getBear() {
		return get("bear");
	}

	public void setBearSupply(java.lang.String bearSupply) {
		set("bearSupply", bearSupply);
	}

	public java.lang.String getBearSupply() {
		return get("bearSupply");
	}

	public void setDeformity(java.lang.String deformity) {
		set("deformity", deformity);
	}

	public java.lang.String getDeformity() {
		return get("deformity");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}

	public java.lang.String getDetail() {
		return get("detail");
	}

	public void setExzlDiagTime(java.util.Date exzlDiagTime) {
		set("exzlDiagTime", exzlDiagTime);
	}

	public java.util.Date getExzlDiagTime() {
		return get("exzlDiagTime");
	}

	public void setFjhDiagTime(java.util.Date fjhDiagTime) {
		set("fjhDiagTime", fjhDiagTime);
	}

	public java.util.Date getFjhDiagTime() {
		return get("fjhDiagTime");
	}

	public void setFqzDiagTime(java.util.Date fqzDiagTime) {
		set("fqzDiagTime", fqzDiagTime);
	}

	public java.util.Date getFqzDiagTime() {
		return get("fqzDiagTime");
	}

	public void setGxbDiagTime(java.util.Date gxbDiagTime) {
		set("gxbDiagTime", gxbDiagTime);
	}

	public java.util.Date getGxbDiagTime() {
		return get("gxbDiagTime");
	}

	public void setGxyDiagTime(java.util.Date gxyDiagTime) {
		set("gxyDiagTime", gxyDiagTime);
	}

	public java.util.Date getGxyDiagTime() {
		return get("gxyDiagTime");
	}

	public void setGxzDiagTime(java.util.Date gxzDiagTime) {
		set("gxzDiagTime", gxzDiagTime);
	}

	public java.util.Date getGxzDiagTime() {
		return get("gxzDiagTime");
	}

	public void setHasExzl(java.lang.String hasExzl) {
		set("hasExzl", hasExzl);
	}

	public java.lang.String getHasExzl() {
		return get("hasExzl");
	}

	public void setHasFjh(java.lang.String hasFjh) {
		set("hasFjh", hasFjh);
	}

	public java.lang.String getHasFjh() {
		return get("hasFjh");
	}

	public void setHasFqz(java.lang.String hasFqz) {
		set("hasFqz", hasFqz);
	}

	public java.lang.String getHasFqz() {
		return get("hasFqz");
	}

	public void setHasGxb(java.lang.String hasGxb) {
		set("hasGxb", hasGxb);
	}

	public java.lang.String getHasGxb() {
		return get("hasGxb");
	}

	public void setHasGxy(java.lang.String hasGxy) {
		set("hasGxy", hasGxy);
	}

	public java.lang.String getHasGxy() {
		return get("hasGxy");
	}

	public void setHasGxz(java.lang.String hasGxz) {
		set("hasGxz", hasGxz);
	}

	public java.lang.String getHasGxz() {
		return get("hasGxz");
	}

	public void setHasMz(java.lang.String hasMz) {
		set("hasMz", hasMz);
	}

	public java.lang.String getHasMz() {
		return get("hasMz");
	}

	public void setHasNzf(java.lang.String hasNzf) {
		set("hasNzf", hasNzf);
	}

	public java.lang.String getHasNzf() {
		return get("hasNzf");
	}

	public void setHasTnbI(java.lang.String hasTnbI) {
		set("hasTnbI", hasTnbI);
	}

	public java.lang.String getHasTnbI() {
		return get("hasTnbI");
	}

	public void setHasTnbII(java.lang.String hasTnbII) {
		set("hasTnbII", hasTnbII);
	}

	public java.lang.String getHasTnbII() {
		return get("hasTnbII");
	}

	public void setHasXc(java.lang.String hasXc) {
		set("hasXc", hasXc);
	}

	public java.lang.String getHasXc() {
		return get("hasXc");
	}

	public void setJcAllergen(java.lang.String jcAllergen) {
		set("jcAllergen", jcAllergen);
	}

	public java.lang.String getJcAllergen() {
		return get("jcAllergen");
	}

	public void setMenstrual(java.lang.String menstrual) {
		set("menstrual", menstrual);
	}

	public java.lang.String getMenstrual() {
		return get("menstrual");
	}

	public void setMzDiagTime(java.util.Date mzDiagTime) {
		set("mzDiagTime", mzDiagTime);
	}

	public java.util.Date getMzDiagTime() {
		return get("mzDiagTime");
	}

	public void setNzfDiagTime(java.util.Date nzfDiagTime) {
		set("nzfDiagTime", nzfDiagTime);
	}

	public java.util.Date getNzfDiagTime() {
		return get("nzfDiagTime");
	}

	public void setOther(java.lang.String other) {
		set("other", other);
	}

	public java.lang.String getOther() {
		return get("other");
	}

	public void setOtherDialogTime(java.util.Date otherDialogTime) {
		set("otherDialogTime", otherDialogTime);
	}

	public java.util.Date getOtherDialogTime() {
		return get("otherDialogTime");
	}

	public void setSelfAllergen(java.lang.String selfAllergen) {
		set("selfAllergen", selfAllergen);
	}

	public java.lang.String getSelfAllergen() {
		return get("selfAllergen");
	}

	public void setSelfAllergy(java.lang.String selfAllergy) {
		set("selfAllergy", selfAllergy);
	}

	public java.lang.String getSelfAllergy() {
		return get("selfAllergy");
	}

	public void setSrAllergen(java.lang.String srAllergen) {
		set("srAllergen", srAllergen);
	}

	public java.lang.String getSrAllergen() {
		return get("srAllergen");
	}

	public void setSrAllergy(java.lang.String srAllergy) {
		set("srAllergy", srAllergy);
	}

	public java.lang.String getSrAllergy() {
		return get("srAllergy");
	}

	public void setSupply(java.lang.String supply) {
		set("supply", supply);
	}

	public java.lang.String getSupply() {
		return get("supply");
	}

	public void setSurgery(java.lang.Boolean surgery) {
		set("surgery", surgery);
	}

	public java.lang.Boolean getSurgery() {
		return get("surgery");
	}

	public void setSurgeryDetail(java.lang.String surgeryDetail) {
		set("surgeryDetail", surgeryDetail);
	}

	public java.lang.String getSurgeryDetail() {
		return get("surgeryDetail");
	}

	public void setTnbIDiagTime(java.util.Date tnbIDiagTime) {
		set("tnbIDiagTime", tnbIDiagTime);
	}

	public java.util.Date getTnbIDiagTime() {
		return get("tnbIDiagTime");
	}

	public void setTnbIIiagTime(java.util.Date tnbIIiagTime) {
		set("tnbIIiagTime", tnbIIiagTime);
	}

	public java.util.Date getTnbIIiagTime() {
		return get("tnbIIiagTime");
	}

	public void setTransfusionOfBlood(java.lang.Boolean transfusionOfBlood) {
		set("transfusionOfBlood", transfusionOfBlood);
	}

	public java.lang.Boolean getTransfusionOfBlood() {
		return get("transfusionOfBlood");
	}

	public void setTrauma(java.lang.Boolean trauma) {
		set("trauma", trauma);
	}

	public java.lang.Boolean getTrauma() {
		return get("trauma");
	}

	public void setXcDiagTime(java.util.Date xcDiagTime) {
		set("xcDiagTime", xcDiagTime);
	}

	public java.util.Date getXcDiagTime() {
		return get("xcDiagTime");
	}

	public void setXrAllergen(java.lang.String xrAllergen) {
		set("xrAllergen", xrAllergen);
	}

	public java.lang.String getXrAllergen() {
		return get("xrAllergen");
	}

	public void setXrAllergy(java.lang.String xrAllergy) {
		set("xrAllergy", xrAllergy);
	}

	public java.lang.String getXrAllergy() {
		return get("xrAllergy");
	}

	public void setZsAllergen(java.lang.String zsAllergen) {
		set("zsAllergen", zsAllergen);
	}

	public java.lang.String getZsAllergen() {
		return get("zsAllergen");
	}

	public void setZsAllergy(java.lang.String zsAllergy) {
		set("zsAllergy", zsAllergy);
	}

	public java.lang.String getZsAllergy() {
		return get("zsAllergy");
	}

	public void setJcAllergy(java.lang.String jcAllergy) {
		set("jcAllergy", jcAllergy);
	}

	public java.lang.String getJcAllergy() {
		return get("jcAllergy");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsHasMedical(java.lang.Integer isHasMedical) {
		set("isHasMedical", isHasMedical);
	}

	public java.lang.Integer getIsHasMedical() {
		return get("isHasMedical");
	}

	public void setIsHasAllergy(java.lang.Integer isHasAllergy) {
		set("isHasAllergy", isHasAllergy);
	}

	public java.lang.Integer getIsHasAllergy() {
		return get("isHasAllergy");
	}

	public void setIsHasFamilyHealth(java.lang.Integer isHasFamilyHealth) {
		set("isHasFamilyHealth", isHasFamilyHealth);
	}

	public java.lang.Integer getIsHasFamilyHealth() {
		return get("isHasFamilyHealth");
	}

	public void setHopeSolveHealth(java.lang.String hopeSolveHealth) {
		set("hopeSolveHealth", hopeSolveHealth);
	}

	public java.lang.String getHopeSolveHealth() {
		return get("hopeSolveHealth");
	}

	public void setAllergenOther(java.lang.String allergenOther) {
		set("allergenOther", allergenOther);
	}

	public java.lang.String getAllergenOther() {
		return get("allergenOther");
	}

}
