package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientExtend<M extends BaseClientExtend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setLastFollowTime(java.util.Date lastFollowTime) {
		set("lastFollowTime", lastFollowTime);
	}

	public java.util.Date getLastFollowTime() {
		return get("lastFollowTime");
	}

	public void setLastUploadDateTime(java.util.Date lastUploadDateTime) {
		set("lastUploadDateTime", lastUploadDateTime);
	}

	public java.util.Date getLastUploadDateTime() {
		return get("lastUploadDateTime");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return get("source");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return get("version");
	}

	public void setRegTime(java.util.Date regTime) {
		set("regTime", regTime);
	}

	public java.util.Date getRegTime() {
		return get("regTime");
	}

	public void setInitiativeinvite(java.lang.String initiativeinvite) {
		set("initiativeinvite", initiativeinvite);
	}

	public java.lang.String getInitiativeinvite() {
		return get("initiativeinvite");
	}

	public void setPassivityinvite(java.lang.String passivityinvite) {
		set("passivityinvite", passivityinvite);
	}

	public java.lang.String getPassivityinvite() {
		return get("passivityinvite");
	}

	public void setTotalScore(java.lang.Integer totalScore) {
		set("totalScore", totalScore);
	}

	public java.lang.Integer getTotalScore() {
		return get("totalScore");
	}

	public void setRemainScore(java.lang.Integer remainScore) {
		set("remainScore", remainScore);
	}

	public java.lang.Integer getRemainScore() {
		return get("remainScore");
	}

	public void setTotalCoins(java.lang.Integer totalCoins) {
		set("totalCoins", totalCoins);
	}

	public java.lang.Integer getTotalCoins() {
		return get("totalCoins");
	}

	public void setRemainCoins(java.lang.Integer remainCoins) {
		set("remainCoins", remainCoins);
	}

	public java.lang.Integer getRemainCoins() {
		return get("remainCoins");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setReportScore(java.lang.Integer reportScore) {
		set("reportScore", reportScore);
	}

	public java.lang.Integer getReportScore() {
		return get("reportScore");
	}

	public void setDietScore(java.lang.Integer dietScore) {
		set("dietScore", dietScore);
	}

	public java.lang.Integer getDietScore() {
		return get("dietScore");
	}

	public void setDoctorScore(java.lang.Integer doctorScore) {
		set("doctorScore", doctorScore);
	}

	public java.lang.Integer getDoctorScore() {
		return get("doctorScore");
	}

	public void setSportScore(java.lang.Integer sportScore) {
		set("sportScore", sportScore);
	}

	public java.lang.Integer getSportScore() {
		return get("sportScore");
	}

	public void setBalance(java.lang.Double balance) {
		set("balance", balance);
	}

	public java.lang.Double getBalance() {
		return get("balance");
	}

}
