package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientFamilyHealth<M extends BaseClientFamilyHealth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setFaExzlAge(java.lang.Integer faExzlAge) {
		set("faExzlAge", faExzlAge);
	}

	public java.lang.Integer getFaExzlAge() {
		return get("faExzlAge");
	}

	public void setFaGxbAge(java.lang.Integer faGxbAge) {
		set("faGxbAge", faGxbAge);
	}

	public java.lang.Integer getFaGxbAge() {
		return get("faGxbAge");
	}

	public void setFaGxyAge(java.lang.Integer faGxyAge) {
		set("faGxyAge", faGxyAge);
	}

	public java.lang.Integer getFaGxyAge() {
		return get("faGxyAge");
	}

	public void setFaGyAge(java.lang.Integer faGyAge) {
		set("faGyAge", faGyAge);
	}

	public java.lang.Integer getFaGyAge() {
		return get("faGyAge");
	}

	public void setFaHasExzl(java.lang.String faHasExzl) {
		set("faHasExzl", faHasExzl);
	}

	public java.lang.String getFaHasExzl() {
		return get("faHasExzl");
	}

	public void setFaHasGxb(java.lang.String faHasGxb) {
		set("faHasGxb", faHasGxb);
	}

	public java.lang.String getFaHasGxb() {
		return get("faHasGxb");
	}

	public void setFaHasGxy(java.lang.String faHasGxy) {
		set("faHasGxy", faHasGxy);
	}

	public java.lang.String getFaHasGxy() {
		return get("faHasGxy");
	}

	public void setFaHasGy(java.lang.String faHasGy) {
		set("faHasGy", faHasGy);
	}

	public java.lang.String getFaHasGy() {
		return get("faHasGy");
	}

	public void setFaHasJhb(java.lang.String faHasJhb) {
		set("faHasJhb", faHasJhb);
	}

	public java.lang.String getFaHasJhb() {
		return get("faHasJhb");
	}

	public void setFaHasJsb(java.lang.String faHasJsb) {
		set("faHasJsb", faHasJsb);
	}

	public java.lang.String getFaHasJsb() {
		return get("faHasJsb");
	}

	public void setFaHasNxg(java.lang.String faHasNxg) {
		set("faHasNxg", faHasNxg);
	}

	public java.lang.String getFaHasNxg() {
		return get("faHasNxg");
	}

	public void setFaHasOther(java.lang.String faHasOther) {
		set("faHasOther", faHasOther);
	}

	public java.lang.String getFaHasOther() {
		return get("faHasOther");
	}

	public void setFaHasTnb(java.lang.String faHasTnb) {
		set("faHasTnb", faHasTnb);
	}

	public java.lang.String getFaHasTnb() {
		return get("faHasTnb");
	}

	public void setFaJhbAge(java.lang.Integer faJhbAge) {
		set("faJhbAge", faJhbAge);
	}

	public java.lang.Integer getFaJhbAge() {
		return get("faJhbAge");
	}

	public void setFaJsbAge(java.lang.Integer faJsbAge) {
		set("faJsbAge", faJsbAge);
	}

	public java.lang.Integer getFaJsbAge() {
		return get("faJsbAge");
	}

	public void setFaNxgAge(java.lang.Integer faNxgAge) {
		set("faNxgAge", faNxgAge);
	}

	public java.lang.Integer getFaNxgAge() {
		return get("faNxgAge");
	}

	public void setFaOtherAge(java.lang.Integer faOtherAge) {
		set("faOtherAge", faOtherAge);
	}

	public java.lang.Integer getFaOtherAge() {
		return get("faOtherAge");
	}

	public void setFaTnbAge(java.lang.Integer faTnbAge) {
		set("faTnbAge", faTnbAge);
	}

	public java.lang.Integer getFaTnbAge() {
		return get("faTnbAge");
	}

	public void setMoExzlAge(java.lang.Integer moExzlAge) {
		set("moExzlAge", moExzlAge);
	}

	public java.lang.Integer getMoExzlAge() {
		return get("moExzlAge");
	}

	public void setMoGxbAge(java.lang.Integer moGxbAge) {
		set("moGxbAge", moGxbAge);
	}

	public java.lang.Integer getMoGxbAge() {
		return get("moGxbAge");
	}

	public void setMoGxyAge(java.lang.Integer moGxyAge) {
		set("moGxyAge", moGxyAge);
	}

	public java.lang.Integer getMoGxyAge() {
		return get("moGxyAge");
	}

	public void setMoGyAge(java.lang.Integer moGyAge) {
		set("moGyAge", moGyAge);
	}

	public java.lang.Integer getMoGyAge() {
		return get("moGyAge");
	}

	public void setMoHasExzl(java.lang.String moHasExzl) {
		set("moHasExzl", moHasExzl);
	}

	public java.lang.String getMoHasExzl() {
		return get("moHasExzl");
	}

	public void setMoHasGxb(java.lang.String moHasGxb) {
		set("moHasGxb", moHasGxb);
	}

	public java.lang.String getMoHasGxb() {
		return get("moHasGxb");
	}

	public void setMoHasGxy(java.lang.String moHasGxy) {
		set("moHasGxy", moHasGxy);
	}

	public java.lang.String getMoHasGxy() {
		return get("moHasGxy");
	}

	public void setMoHasGy(java.lang.String moHasGy) {
		set("moHasGy", moHasGy);
	}

	public java.lang.String getMoHasGy() {
		return get("moHasGy");
	}

	public void setMoHasJhb(java.lang.String moHasJhb) {
		set("moHasJhb", moHasJhb);
	}

	public java.lang.String getMoHasJhb() {
		return get("moHasJhb");
	}

	public void setMoHasJsb(java.lang.String moHasJsb) {
		set("moHasJsb", moHasJsb);
	}

	public java.lang.String getMoHasJsb() {
		return get("moHasJsb");
	}

	public void setMoHasNxg(java.lang.String moHasNxg) {
		set("moHasNxg", moHasNxg);
	}

	public java.lang.String getMoHasNxg() {
		return get("moHasNxg");
	}

	public void setMoHasOther(java.lang.String moHasOther) {
		set("moHasOther", moHasOther);
	}

	public java.lang.String getMoHasOther() {
		return get("moHasOther");
	}

	public void setMoHasTnb(java.lang.String moHasTnb) {
		set("moHasTnb", moHasTnb);
	}

	public java.lang.String getMoHasTnb() {
		return get("moHasTnb");
	}

	public void setMoJhbAge(java.lang.Integer moJhbAge) {
		set("moJhbAge", moJhbAge);
	}

	public java.lang.Integer getMoJhbAge() {
		return get("moJhbAge");
	}

	public void setMoJsbAge(java.lang.Integer moJsbAge) {
		set("moJsbAge", moJsbAge);
	}

	public java.lang.Integer getMoJsbAge() {
		return get("moJsbAge");
	}

	public void setMoNxgAge(java.lang.Integer moNxgAge) {
		set("moNxgAge", moNxgAge);
	}

	public java.lang.Integer getMoNxgAge() {
		return get("moNxgAge");
	}

	public void setMoOtherAge(java.lang.Integer moOtherAge) {
		set("moOtherAge", moOtherAge);
	}

	public java.lang.Integer getMoOtherAge() {
		return get("moOtherAge");
	}

	public void setMoTnbAge(java.lang.Integer moTnbAge) {
		set("moTnbAge", moTnbAge);
	}

	public java.lang.Integer getMoTnbAge() {
		return get("moTnbAge");
	}

	public void setOther(java.lang.String other) {
		set("other", other);
	}

	public java.lang.String getOther() {
		return get("other");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsHasFamilyHealth(java.lang.Integer isHasFamilyHealth) {
		set("isHasFamilyHealth", isHasFamilyHealth);
	}

	public java.lang.Integer getIsHasFamilyHealth() {
		return get("isHasFamilyHealth");
	}

}
