package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateUserChain(java.lang.String createUserChain) {
		set("createUserChain", createUserChain);
	}

	public java.lang.String getCreateUserChain() {
		return get("createUserChain");
	}

	public void setIsSelfManage(java.lang.Integer isSelfManage) {
		set("isSelfManage", isSelfManage);
	}

	public java.lang.Integer getIsSelfManage() {
		return get("isSelfManage");
	}

	public void setHasSettingAssign(java.lang.Integer hasSettingAssign) {
		set("hasSettingAssign", hasSettingAssign);
	}

	public java.lang.Integer getHasSettingAssign() {
		return get("hasSettingAssign");
	}

}
