package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientServiceRemind<M extends BaseClientServiceRemind<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setProductId(java.lang.Integer productId) {
		set("productId", productId);
	}

	public java.lang.Integer getProductId() {
		return get("productId");
	}

	public void setOmId(java.lang.Integer omId) {
		set("omId", omId);
	}

	public java.lang.Integer getOmId() {
		return get("omId");
	}

	public void setPurchaseTime(java.util.Date purchaseTime) {
		set("purchaseTime", purchaseTime);
	}

	public java.util.Date getPurchaseTime() {
		return get("purchaseTime");
	}

	public void setExpiresTime(java.util.Date expiresTime) {
		set("expiresTime", expiresTime);
	}

	public java.util.Date getExpiresTime() {
		return get("expiresTime");
	}

	public void setRemainingDays(java.lang.Integer remainingDays) {
		set("remainingDays", remainingDays);
	}

	public java.lang.Integer getRemainingDays() {
		return get("remainingDays");
	}

	public void setFlag(java.lang.Boolean flag) {
		set("flag", flag);
	}

	public java.lang.Boolean getFlag() {
		return get("flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
