package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientDiseaseSelf<M extends BaseClientDiseaseSelf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setDisease(java.lang.String disease) {
		set("disease", disease);
	}

	public java.lang.String getDisease() {
		return get("disease");
	}

	public void setDiagTime(java.util.Date diagTime) {
		set("diagTime", diagTime);
	}

	public java.util.Date getDiagTime() {
		return get("diagTime");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

}
