package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientUpload<M extends BaseClientUpload<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setDealRemark(java.lang.String dealRemark) {
		set("dealRemark", dealRemark);
	}

	public java.lang.String getDealRemark() {
		return get("dealRemark");
	}

	public void setDealTime(java.util.Date dealTime) {
		set("dealTime", dealTime);
	}

	public java.util.Date getDealTime() {
		return get("dealTime");
	}

	public void setDealUser(java.lang.Integer dealUser) {
		set("dealUser", dealUser);
	}

	public java.lang.Integer getDealUser() {
		return get("dealUser");
	}

	public void setFilePath(java.lang.String filePath) {
		set("filePath", filePath);
	}

	public java.lang.String getFilePath() {
		return get("filePath");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}

	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

}
