package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientQuestionnaire<M extends BaseClientQuestionnaire<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setFamilyHistory(java.lang.String familyHistory) {
		set("familyHistory", familyHistory);
	}

	public java.lang.String getFamilyHistory() {
		return get("familyHistory");
	}

	public void setEspathology(java.lang.String espathology) {
		set("espathology", espathology);
	}

	public java.lang.String getEspathology() {
		return get("espathology");
	}

	public void setDailydiet(java.lang.String dailydiet) {
		set("dailydiet", dailydiet);
	}

	public java.lang.String getDailydiet() {
		return get("dailydiet");
	}

	public void setLifestyleInfo(java.lang.String lifestyleInfo) {
		set("lifestyleInfo", lifestyleInfo);
	}

	public java.lang.String getLifestyleInfo() {
		return get("lifestyleInfo");
	}

	public void setCreatTime(java.util.Date creatTime) {
		set("creatTime", creatTime);
	}

	public java.util.Date getCreatTime() {
		return get("creatTime");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

}
