package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientHobby<M extends BaseClientHobby<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}

	public java.lang.Integer getClientId() {
		return get("clientId");
	}

	public void setSmoke(java.lang.Integer smoke) {
		set("smoke", smoke);
	}

	public java.lang.Integer getSmoke() {
		return get("smoke");
	}

	public void setAverage(java.lang.Integer average) {
		set("average", average);
	}

	public java.lang.Integer getAverage() {
		return get("average");
	}

	public void setBeer(java.lang.String beer) {
		set("beer", beer);
	}

	public java.lang.String getBeer() {
		return get("beer");
	}

	public void setCigaret(java.lang.String cigaret) {
		set("cigaret", cigaret);
	}

	public java.lang.String getCigaret() {
		return get("cigaret");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setDage(java.lang.Integer dage) {
		set("dage", dage);
	}

	public java.lang.Integer getDage() {
		return get("dage");
	}

	public void setDiet(java.lang.String diet) {
		set("diet", diet);
	}

	public java.lang.String getDiet() {
		return get("diet");
	}

	public void setDrink(java.lang.Integer drink) {
		set("drink", drink);
	}

	public java.lang.Integer getDrink() {
		return get("drink");
	}

	public void setReSmoking(java.lang.Integer reSmoking) {
		set("reSmoking", reSmoking);
	}

	public java.lang.Integer getReSmoking() {
		return get("reSmoking");
	}

	public void setRed(java.lang.String red) {
		set("red", red);
	}

	public java.lang.String getRed() {
		return get("red");
	}

	public void setSage(java.lang.Integer sage) {
		set("sage", sage);
	}

	public java.lang.Integer getSage() {
		return get("sage");
	}

	public void setShAge(java.lang.Integer shAge) {
		set("shAge", shAge);
	}

	public java.lang.Integer getShAge() {
		return get("shAge");
	}

	public void setShDay(java.lang.Integer shDay) {
		set("shDay", shDay);
	}

	public java.lang.Integer getShDay() {
		return get("shDay");
	}

	public void setShMinuite(java.lang.Integer shMinuite) {
		set("shMinuite", shMinuite);
	}

	public java.lang.Integer getShMinuite() {
		return get("shMinuite");
	}

	public void setShSmoke(java.lang.Integer shSmoke) {
		set("shSmoke", shSmoke);
	}

	public java.lang.Integer getShSmoke() {
		return get("shSmoke");
	}

	public void setSleeping(java.lang.Integer sleeping) {
		set("sleeping", sleeping);
	}

	public java.lang.Integer getSleeping() {
		return get("sleeping");
	}

	public void setSportCount(java.lang.Integer sportCount) {
		set("sportCount", sportCount);
	}

	public java.lang.Integer getSportCount() {
		return get("sportCount");
	}

	public void setSportSupply(java.lang.String sportSupply) {
		set("sportSupply", sportSupply);
	}

	public java.lang.String getSportSupply() {
		return get("sportSupply");
	}

	public void setSportTime(java.lang.Integer sportTime) {
		set("sportTime", sportTime);
	}

	public java.lang.Integer getSportTime() {
		return get("sportTime");
	}

	public void setSportType(java.lang.String sportType) {
		set("sportType", sportType);
	}

	public java.lang.String getSportType() {
		return get("sportType");
	}

	public void setWhite(java.lang.String white) {
		set("white", white);
	}

	public java.lang.String getWhite() {
		return get("white");
	}

	public void setWorking(java.lang.Integer working) {
		set("working", working);
	}

	public java.lang.Integer getWorking() {
		return get("working");
	}

	public void setSyear(java.lang.Integer syear) {
		set("syear", syear);
	}

	public java.lang.Integer getSyear() {
		return get("syear");
	}

	public void setPhysicalType(java.lang.Integer physicalType) {
		set("physicalType", physicalType);
	}

	public java.lang.Integer getPhysicalType() {
		return get("physicalType");
	}

	public void setNotEat(java.lang.String notEat) {
		set("notEat", notEat);
	}

	public java.lang.String getNotEat() {
		return get("notEat");
	}

	public void setBreakfast(java.lang.String breakfast) {
		set("breakfast", breakfast);
	}

	public java.lang.String getBreakfast() {
		return get("breakfast");
	}

	public void setBreakfastOther(java.lang.String breakfastOther) {
		set("breakfastOther", breakfastOther);
	}

	public java.lang.String getBreakfastOther() {
		return get("breakfastOther");
	}

	public void setLunch(java.lang.String lunch) {
		set("lunch", lunch);
	}

	public java.lang.String getLunch() {
		return get("lunch");
	}

	public void setLunchOther(java.lang.String lunchOther) {
		set("lunchOther", lunchOther);
	}

	public java.lang.String getLunchOther() {
		return get("lunchOther");
	}

	public void setDinner(java.lang.String dinner) {
		set("dinner", dinner);
	}

	public java.lang.String getDinner() {
		return get("dinner");
	}

	public void setDinnerOther(java.lang.String dinnerOther) {
		set("dinnerOther", dinnerOther);
	}

	public java.lang.String getDinnerOther() {
		return get("dinnerOther");
	}

	public void setJiacanCount(java.lang.Integer jiacanCount) {
		set("jiacanCount", jiacanCount);
	}

	public java.lang.Integer getJiacanCount() {
		return get("jiacanCount");
	}

	public void setJiacanType(java.lang.String jiacanType) {
		set("jiacanType", jiacanType);
	}

	public java.lang.String getJiacanType() {
		return get("jiacanType");
	}

	public void setSportTimeZone(java.lang.String sportTimeZone) {
		set("sportTimeZone", sportTimeZone);
	}

	public java.lang.String getSportTimeZone() {
		return get("sportTimeZone");
	}

	public void setSportZoneOther(java.lang.String sportZoneOther) {
		set("sportZoneOther", sportZoneOther);
	}

	public java.lang.String getSportZoneOther() {
		return get("sportZoneOther");
	}

	public void setSportHabit(java.lang.String sportHabit) {
		set("sportHabit", sportHabit);
	}

	public java.lang.String getSportHabit() {
		return get("sportHabit");
	}

	public void setSportHabitOther(java.lang.String sportHabitOther) {
		set("sportHabitOther", sportHabitOther);
	}

	public java.lang.String getSportHabitOther() {
		return get("sportHabitOther");
	}

}
