package com.xtgg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientinfo<M extends BaseClientinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClientCode(java.lang.String clientCode) {
		set("clientCode", clientCode);
	}

	public java.lang.String getClientCode() {
		return get("clientCode");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setVipCard(java.lang.String vipCard) {
		set("vipCard", vipCard);
	}

	public java.lang.String getVipCard() {
		return get("vipCard");
	}

	public void setIdCards(java.lang.String idCards) {
		set("idCards", idCards);
	}

	public java.lang.String getIdCards() {
		return get("idCards");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setBirthPlace(java.lang.String birthPlace) {
		set("birthPlace", birthPlace);
	}

	public java.lang.String getBirthPlace() {
		return get("birthPlace");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setEthnic(java.lang.String ethnic) {
		set("ethnic", ethnic);
	}

	public java.lang.String getEthnic() {
		return get("ethnic");
	}

	public void setFaith(java.lang.String faith) {
		set("faith", faith);
	}

	public java.lang.String getFaith() {
		return get("faith");
	}

	public void setBloodType(java.lang.Integer bloodType) {
		set("bloodType", bloodType);
	}

	public java.lang.Integer getBloodType() {
		return get("bloodType");
	}

	public void setRh(java.lang.Integer rh) {
		set("rh", rh);
	}

	public java.lang.Integer getRh() {
		return get("rh");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setIncome(java.lang.Integer income) {
		set("income", income);
	}

	public java.lang.Integer getIncome() {
		return get("income");
	}

	public void setUsualAddress(java.lang.String usualAddress) {
		set("usualAddress", usualAddress);
	}

	public java.lang.String getUsualAddress() {
		return get("usualAddress");
	}

	public void setPostcode(java.lang.String postcode) {
		set("postcode", postcode);
	}

	public java.lang.String getPostcode() {
		return get("postcode");
	}

	public void setMarriage(java.lang.Integer marriage) {
		set("marriage", marriage);
	}

	public java.lang.Integer getMarriage() {
		return get("marriage");
	}

	public void setCulture(java.lang.Integer culture) {
		set("culture", culture);
	}

	public java.lang.Integer getCulture() {
		return get("culture");
	}

	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}

	public java.lang.String getProfession() {
		return get("profession");
	}

	public void setWorkUnits(java.lang.String workUnits) {
		set("workUnits", workUnits);
	}

	public java.lang.String getWorkUnits() {
		return get("workUnits");
	}

	public void setDuty(java.lang.String duty) {
		set("duty", duty);
	}

	public java.lang.String getDuty() {
		return get("duty");
	}

	public void setUnitsPhone(java.lang.String unitsPhone) {
		set("unitsPhone", unitsPhone);
	}

	public java.lang.String getUnitsPhone() {
		return get("unitsPhone");
	}

	public void setMedicalExpenses(java.lang.Integer medicalExpenses) {
		set("medicalExpenses", medicalExpenses);
	}

	public java.lang.Integer getMedicalExpenses() {
		return get("medicalExpenses");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setAreaId(java.lang.Integer areaId) {
		set("areaId", areaId);
	}

	public java.lang.Integer getAreaId() {
		return get("areaId");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setIntegral(java.lang.Integer integral) {
		set("integral", integral);
	}

	public java.lang.Integer getIntegral() {
		return get("integral");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLevelId(java.lang.Integer levelId) {
		set("levelId", levelId);
	}

	public java.lang.Integer getLevelId() {
		return get("levelId");
	}

	public void setConstellation(java.lang.String constellation) {
		set("constellation", constellation);
	}

	public java.lang.String getConstellation() {
		return get("constellation");
	}

	public void setChineseZodiac(java.lang.String chineseZodiac) {
		set("chineseZodiac", chineseZodiac);
	}

	public java.lang.String getChineseZodiac() {
		return get("chineseZodiac");
	}

	public void setHealthIndex(java.lang.Integer healthIndex) {
		set("healthIndex", healthIndex);
	}

	public java.lang.Integer getHealthIndex() {
		return get("healthIndex");
	}

	public void setAreaChain(java.lang.String areaChain) {
		set("areaChain", areaChain);
	}

	public java.lang.String getAreaChain() {
		return get("areaChain");
	}

	public void setFinishPercent(java.lang.Double finishPercent) {
		set("finishPercent", finishPercent);
	}

	public java.lang.Double getFinishPercent() {
		return get("finishPercent");
	}

	public void setBazzaarGrade(java.lang.String bazzaarGrade) {
		set("bazzaarGrade", bazzaarGrade);
	}

	public java.lang.String getBazzaarGrade() {
		return get("bazzaarGrade");
	}

	public void setPrincipalId(java.lang.Integer principalId) {
		set("principalId", principalId);
	}

	public java.lang.Integer getPrincipalId() {
		return get("principalId");
	}

	public void setHeadPortrait(java.lang.String headPortrait) {
		set("headPortrait", headPortrait);
	}

	public java.lang.String getHeadPortrait() {
		return get("headPortrait");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}

	public java.lang.String getNickName() {
		return get("nickName");
	}

	public void setAvailableProduct(java.lang.String availableProduct) {
		set("availableProduct", availableProduct);
	}

	public java.lang.String getAvailableProduct() {
		return get("availableProduct");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return get("uid");
	}

	public void setCompSource(java.lang.Integer compSource) {
		set("compSource", compSource);
	}

	public java.lang.Integer getCompSource() {
		return get("compSource");
	}

}
